type SupportType = 'string' | 'number' | 'boolean' | 'object' | 'array'
export const excludeKey = ['MODE', 'BASE_URL', 'PROD', 'DEV', 'SSR']
const typeMap: Record<SupportType, string> = {
  boolean: 'boolean',
  string: 'string',
  number: 'number',
  array: 'any[]',
  object: 'Record<string, any>'
}
export function generateDTS(env: Record<string, any>, validationEnv: Record<string, any>, commentRecord: Record<string, string>) {
  let interfaceItem: string[] = []

  // console.log(env)
  for (const envKey of Object.keys(env)) {
    if (excludeKey.includes(envKey)) continue

    const value = env[envKey]
    const comment = commentRecord[envKey]
    let valueType = typeof value as SupportType

    // 精准类型
    const exactType = valueType === 'object' ? (Array.isArray(value) ? 'array' : 'object') : valueType

    const dtsType = validationEnv[envKey] || typeMap[exactType] || 'any'
    const jsDocComment = comment
      ? `/**
   * ${comment}
   */
  `
      : ''
    const keyValue = `readonly ${envKey}: ${dtsType}`

    interfaceItem.push(jsDocComment + keyValue)
  }

  if (!interfaceItem.length) return

  return `interface AutoGenerateImportMetaEnv {
  // Auto generated by vite-plugin-env-parse. ‼️ DO NOT MODIFY THIS FILE ‼️
  ${interfaceItem.join('\n  ')}
}`
}
