import { Recordable } from '../types'

type SupportType = 'string' | 'number' | 'boolean' | 'object' | 'array'
export const excludeKey = ['MODE', 'BASE_URL', 'PROD', 'DEV', 'SSR']
const typeMap: Recordable<SupportType> = {
  boolean: 'boolean',
  string: 'string',
  number: 'number',
  array: 'any[]',
  object: 'Record<string, any>'
}
export function generateDTS(env: Recordable, validationEnv: Recordable, commentRecord: Recordable<string, string>) {
  let interfaceItem: string[] = []

  // console.log(env)
  for (const envKey of Object.keys(env)) {
    if (excludeKey.includes(envKey)) continue

    const value = env[envKey]
    const comment = commentRecord[envKey]
    let valueType = validationEnv[envKey] || (typeof value as SupportType)

    valueType === 'object' && Array.isArray(value) ? 'array' : typeMap[valueType] || 'any'

    const jsDocComment = comment
      ? `/**
   * ${comment}
   */
  `
      : ''
    const keyValue = `readonly ${envKey}: ${valueType}`

    interfaceItem.push(jsDocComment + keyValue)
  }

  if (!interfaceItem.length) return

  return `interface AutoGenerateImportMetaEnv {
  // Auto generated by vite-plugin-env-parse. ‼️ DO NOT MODIFY THIS FILE ‼️
  ${interfaceItem.join('\n  ')}
}`
}
