// update-env.test.ts
import { describe, it, expect, beforeEach } from 'vitest'
import { vol } from 'memfs'
import { fs as memfs } from 'memfs'
import { updateEnvInterface } from './updateEnvInterface'

describe('updateEnvInterface', () => {
  const filepath = '/env.d.ts'
  const autoGeneratedInterface = `interface AutoGenerateImportMetaEnv {
    VITE_API_URL: string;
    VITE_APP_NAME: string;
  }`

  function countStringOccurrences(text: string, target: string): number {
    return text.split(target).length - 1
  }

  beforeEach(() => {
    vol.reset() // 清空虚拟文件系统
  })

  it('should insert both interfaces when file is empty', () => {
    vol.fromJSON({ [filepath]: '' })
    updateEnvInterface(filepath, autoGeneratedInterface, memfs)

    const updated = memfs.readFileSync(filepath, 'utf-8')
    expect(updated).toContain('interface AutoGenerateImportMetaEnv')
    expect(updated).toContain('interface ImportMetaEnv extends AutoGenerateImportMetaEnv')
  })

  it('should replace AutoGenerateImportMetaEnv and insert ImportMetaEnv', () => {
    vol.fromJSON({
      [filepath]: `interface AutoGenerateImportMetaEnv { OLD: string; }`
    })
    updateEnvInterface(filepath, autoGeneratedInterface, memfs)

    const updated = memfs.readFileSync(filepath, 'utf-8')
    expect(updated).toContain('VITE_API_URL')
    expect(updated).toContain('interface ImportMetaEnv extends AutoGenerateImportMetaEnv')
  })

  it('should insert AutoGenerateImportMetaEnv and replace ImportMetaEnv', () => {
    vol.fromJSON({
      [filepath]: `interface ImportMetaEnv { USER_DEFINED: boolean; }`
    })
    updateEnvInterface(filepath, autoGeneratedInterface, memfs)

    const updated = memfs.readFileSync(filepath, 'utf-8')
    expect(updated).toContain('VITE_APP_NAME')
    expect(updated).toContain('extends AutoGenerateImportMetaEnv')
  })

  it('should replace both interfaces if they exist', () => {
    vol.fromJSON({
      [filepath]: `
interface AutoGenerateImportMetaEnv { VITE_API_URL: string; }
interface ImportMetaEnv { VITE_API_URL: '/app' | '/app1'; }
      `
    })
    updateEnvInterface(filepath, autoGeneratedInterface, memfs)
    updateEnvInterface(filepath, autoGeneratedInterface, memfs)

    const updated = memfs.readFileSync(filepath, 'utf-8').toString()
    expect(updated).toContain('VITE_API_URL')
    expect(updated).toContain(`VITE_API_URL: '/app' | '/app1'`)
    expect(updated).toContain('interface AutoGenerateImportMetaEnv')

    expect(countStringOccurrences(updated, 'interface ImportMetaEnv extends AutoGenerateImportMetaEnv'))
    .toBe(1)
  })
})
